version: "3"
services:
  simple-adventure-db2:
    image: "mariadb:10.3.11"
    container_name: simple-adventure-db2
    volumes:
      - ~/docker/simple-adventure-db2:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  simple-adventure-phpmyadmin2:
    image: "phpmyadmin/phpmyadmin"
    container_name: simple-adventure-phpmyadmin2
    depends_on:
      - simple-adventure-db2
    links:
      - simple-adventure-db2
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "3333:80"

  simple-adventure-sock-js:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: simple-adventure-sock-js
    environment:
      - DB_NAME=SimpleAdventure
    depends_on:
      - simple-adventure-db2
    links:
      - simple-adventure-db2
    volumes:
      - ~/www/simple-adventure/:/var/www/html
    ports:
      - "3001:8080"
    stdin_open: true
    tty: true
