services:
  simple-adventure-database:
    image: mariadb:10.3.11
    container_name: simple-adventure-database
    volumes:
      - ~/docker/simple-adventure-database:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  simple-adventure-phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    container_name: simple-adventure-phpmyadmin
    depends_on:
      - simple-adventure-database
    links:
      - simple-adventure-database
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "3333:80"

networks:
  default:
    name: simple-adventure-network
    external: true
