services:
  simple-adventure-game-be2:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: simple-adventure-game-be2
    environment:
      - DB_NAME=SimpleAdventure
      - SERVER_MODE=socket-io
    volumes:
      - ~/www/simple-adventure/game/server/:/app
    ports:
      - "3002:8080"
    stdin_open: true
    tty: true
    env_file:
      - ./src/socket-io/.env

networks:
  default:
    name: simple-adventure-network
    external: true
