services:
  simple-adventure-game-be:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: simple-adventure-game-be
    environment:
      - DB_NAME=SimpleAdventure
      - SERVER_MODE=sock-js
    volumes:
      - ~/www/simple-adventure/game/server/:/app
    ports:
      - "3001:8080"
    stdin_open: true
    tty: true
    env_file:
      - ./src/sock-js/.env

networks:
  default:
    name: simple-adventure-network
    external: true
